version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: football-log-db
    environment:
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football123
      POSTGRES_DB: football_log
    ports:
      - '5432:5432'
    volumes:
      - football_data:/var/lib/postgresql/data

volumes:
  football_data:
